import type { DefaultTheme } from 'vitepress'
import { generateSidebar } from 'vitepress-sidebar'

export const sidebar: DefaultTheme.Config['sidebar'] = generateSidebar([
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'al',
    resolvePath: '/al/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'ds',
    resolvePath: '/ds/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'os',
    resolvePath: '/os/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'cn',
    resolvePath: '/cn/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'co',
    resolvePath: '/co/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'html',
    resolvePath: '/html/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
  {
    collapsed: true,
    documentRootPath: '/docs',
    scanStartPath: 'blog',
    resolvePath: '/blog/',
    excludeFiles: ['README.md'],
    excludeFolders: ['img'],
    sortMenusByFrontmatterOrder: true,
    useTitleFromFileHeading: true,
  },
])
